theme = "risotto"
baseURL = "https://blog.enriquesanz.com"
title = "Enrique Sanz"
author = "Enrique Sanz"
copyright = "© Enrique Sanz"
defaultContentLanguage = "es"
languageCode = "es"

enableRobotsTXT = true
enableInlineShortcodes = true

sectionPagesMenu = "main"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5
