noindex = false

[theme]
palette = "base16-dark"

[about]
title = "Enrique Sanz"
description = "Blog personal de Enrique Sanz."
logo = "🖥️"

[[socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/enriquesanz"
